# Generated by Django 4.2.20 on 2025-04-24 00:14

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='due_date',
            field=models.DateTimeField(default=datetime.now),
        ),
    ]
