# Generated by Django 4.2.20 on 2025-04-24 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sample_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='due_date',
        ),
    ]
