# Generated by Django 4.2.20 on 2025-04-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_sample_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
