# Generated by Django 4.2.20 on 2025-04-24 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_sample_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 5, 54, 43, 494663)),
        ),
    ]
