# Generated by Django 4.2.20 on 2025-04-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
