# Generated by Django 4.2.20 on 2025-04-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_task_created_at_remove_task_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
