# Generated by Django 4.2.20 on 2025-05-01 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tag_task_tag_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
