# Generated by Django 4.2.20 on 2025-05-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_tag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_tag_link',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sample'),
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
