# Generated by Django 4.2.20 on 2025-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_task_alter_task_tag_link_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(null=True, to='base.tag'),
        ),
    ]
