# Generated by Django 4.2.20 on 2025-05-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='completed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
