# Generated by Django 4.2.20 on 2025-05-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_sample_completed_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=0),
        ),
    ]
